name: Terraform deploy
on:
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v5

          - name: setup Terraform
            uses: hashicorp/setup-terraform@v4

          - name: terraform init
            working-directory: ./terraform
            run: terraform init

          - name: terraform apply
            working-directory: ./terraform
            run: terraform apply