name: Terraform deploy
on:
    workflow_dispatch:
jobs:
    deplpoy:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v5
          - name: setup Terraform
            uses: hashicorp/setup-terraform@v4
          - name: terraform init
            run: terraform init
          - name: terraform apply
            run: terraform apply