name: Check Terraform infrastructue
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      #1
      - name: checkout code
        uses: actions/checkout@v5
      #2
      - name: terraform install
        uses: hashicorp/setup-terraform@v4
      #3
      - name: terraform fmt
        run: terraform fmt -check -recursive #check format
      #4
      - name: terraform init
        run: terraform init
      #5
      - name: terraform validate
        run: terraform validate
      #6
      - name: tflint setup
        uses: terraform-linters/setup-tflint@v6
      #7
      - name: tflint init
        run: tflint --init
      #8
      - name: runt tflint
        run: tflint --recursive
      #9
      - name: checkov
        uses: bridgecrewio/checkov@v12


